packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  protobufjs: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - tsx@4.23.13
